algorithm: RandomForestClassifier
hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42
cross_validation:
  method: StratifiedKFold
  n_splits: 5
target_column: Attrition # Define here the target column